version: "3.9"
services:
  db-test:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=iliketests
      - POSTGRES_DB=test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web-test:
    build: .
    command: bash -c "alembic upgrade head && python -m pytest"
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    environment:
      - TESTING_ENV=1
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    depends_on:
      db-test:
        condition: service_healthy