version: "3.9"
services:
  db-test:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    env_file: test.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web-test:
    build: .
    command: bash -c "alembic upgrade head && python -m pytest"
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    env_file: test.env
    depends_on:
      db-test:
        condition: service_healthy
      cache-test:
        condition: service_healthy
  cache-test:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
