version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: bash -c "alembic upgrade head && python -m pytest"
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    depends_on:
      db:
        condition: service_healthy